version: '3.7'
services:
    ui-tests:
      build: 
        context: .
        dockerfile: ui-tests.Dockerfile
      environment:
        CYPRESS_baseUrl: 'http://hotel-test.equalexperts.io'
      volumes:
        - ${PWD}/ui-tests:/ui-tests
        - ${PWD}/test-framework-lib:/test-framework-lib
        # use the node_modules from inside the container and not from local machine
        - /ui-tests/node_modules
    ui-tests-m1:
      build: 
        context: .
        dockerfile: ui-tests-m1.Dockerfile
      environment:
        CYPRESS_baseUrl: 'http://hotel-test.equalexperts.io'
      volumes:
        - ${PWD}/ui-tests:/ui-tests
        - ${PWD}/test-framework-lib:/test-framework-lib
        # use the node_modules from inside the container and not from local machine
        - /ui-tests/node_modules
        
    api-tests:
      build: 
        context: .
        dockerfile: api-tests.Dockerfile
      environment: 
        API_BASE_URL: 'http://hotel-test.equalexperts.io'
      volumes:
        - ${PWD}/api-tests:/api-tests
        # use the node_modules from inside the container and not from local machine
        - /api-tests/node_modules
    
